### ISSUE TITLE
你好当使用了该组件，是否代表着可以直接将默认的pages.json设置git忽略了

### ISSUE THREAD

**Issue by seepine** [uni-ku/pages-json#2]

**Comment by edwinhuish** [comment]
可以。

但是由于uniapp自身的设定，它凌驾于vite之上，在vite没启动之前会先执行操作，没pages.json会报错。

解决方案可以是：

1. 创建项目后，先创建一个空白的 pages.json 文件 (仅需一次）
2. 在 `package.json` 的 script 里加个shell，每次 `touch` 一下 `pages.json`
